/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RankCompetitorList } from './RankCompetitorList';
import {
    RankCompetitorListFromJSON,
    RankCompetitorListFromJSONTyped,
    RankCompetitorListToJSON,
} from './RankCompetitorList';
import type { RankFeatureList } from './RankFeatureList';
import {
    RankFeatureListFromJSON,
    RankFeatureListFromJSONTyped,
    RankFeatureListToJSON,
} from './RankFeatureList';

/**
 * 
 * @export
 * @interface BodyFilterSearchByCompetitorFilterCompetitorPost
 */
export interface BodyFilterSearchByCompetitorFilterCompetitorPost {
    /**
     * 
     * @type {RankFeatureList}
     * @memberof BodyFilterSearchByCompetitorFilterCompetitorPost
     */
    features: RankFeatureList;
    /**
     * 
     * @type {RankCompetitorList}
     * @memberof BodyFilterSearchByCompetitorFilterCompetitorPost
     */
    competitor: RankCompetitorList;
}

/**
 * Check if a given object implements the BodyFilterSearchByCompetitorFilterCompetitorPost interface.
 */
export function instanceOfBodyFilterSearchByCompetitorFilterCompetitorPost(value: object): value is BodyFilterSearchByCompetitorFilterCompetitorPost {
    if (!('features' in value) || value['features'] === undefined) return false;
    if (!('competitor' in value) || value['competitor'] === undefined) return false;
    return true;
}

export function BodyFilterSearchByCompetitorFilterCompetitorPostFromJSON(json: any): BodyFilterSearchByCompetitorFilterCompetitorPost {
    return BodyFilterSearchByCompetitorFilterCompetitorPostFromJSONTyped(json, false);
}

export function BodyFilterSearchByCompetitorFilterCompetitorPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyFilterSearchByCompetitorFilterCompetitorPost {
    if (json == null) {
        return json;
    }
    return {
        
        'features': RankFeatureListFromJSON(json['features']),
        'competitor': RankCompetitorListFromJSON(json['competitor']),
    };
}

export function BodyFilterSearchByCompetitorFilterCompetitorPostToJSON(value?: BodyFilterSearchByCompetitorFilterCompetitorPost | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'features': RankFeatureListToJSON(value['features']),
        'competitor': RankCompetitorListToJSON(value['competitor']),
    };
}

