/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DescriptionOfACompany
 */
export interface DescriptionOfACompany {
    /**
     * 
     * @type {number}
     * @memberof DescriptionOfACompany
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof DescriptionOfACompany
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DescriptionOfACompany
     */
    website: string;
    /**
     * 
     * @type {string}
     * @memberof DescriptionOfACompany
     */
    summary: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DescriptionOfACompany
     */
    features: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DescriptionOfACompany
     */
    uniqueVisitor: number;
}

/**
 * Check if a given object implements the DescriptionOfACompany interface.
 */
export function instanceOfDescriptionOfACompany(value: object): value is DescriptionOfACompany {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('features' in value) || value['features'] === undefined) return false;
    if (!('uniqueVisitor' in value) || value['uniqueVisitor'] === undefined) return false;
    return true;
}

export function DescriptionOfACompanyFromJSON(json: any): DescriptionOfACompany {
    return DescriptionOfACompanyFromJSONTyped(json, false);
}

export function DescriptionOfACompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DescriptionOfACompany {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'website': json['website'],
        'summary': json['summary'],
        'features': json['features'],
        'uniqueVisitor': json['uniqueVisitor'],
    };
}

export function DescriptionOfACompanyToJSON(value?: DescriptionOfACompany | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'website': value['website'],
        'summary': value['summary'],
        'features': value['features'],
        'uniqueVisitor': value['uniqueVisitor'],
    };
}

