/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Feature } from './Feature';
import {
    FeatureFromJSON,
    FeatureFromJSONTyped,
    FeatureToJSON,
} from './Feature';

/**
 * 
 * @export
 * @interface RankFeatureList
 */
export interface RankFeatureList {
    /**
     * 
     * @type {Array<Feature>}
     * @memberof RankFeatureList
     */
    features: Array<Feature>;
}

/**
 * Check if a given object implements the RankFeatureList interface.
 */
export function instanceOfRankFeatureList(value: object): value is RankFeatureList {
    if (!('features' in value) || value['features'] === undefined) return false;
    return true;
}

export function RankFeatureListFromJSON(json: any): RankFeatureList {
    return RankFeatureListFromJSONTyped(json, false);
}

export function RankFeatureListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RankFeatureList {
    if (json == null) {
        return json;
    }
    return {
        
        'features': ((json['features'] as Array<any>).map(FeatureFromJSON)),
    };
}

export function RankFeatureListToJSON(value?: RankFeatureList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'features': ((value['features'] as Array<any>).map(FeatureToJSON)),
    };
}

