/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DescriptionOfACompany } from './DescriptionOfACompany';
import {
    DescriptionOfACompanyFromJSON,
    DescriptionOfACompanyFromJSONTyped,
    DescriptionOfACompanyToJSON,
} from './DescriptionOfACompany';

/**
 * 
 * @export
 * @interface RankCompetitorList
 */
export interface RankCompetitorList {
    /**
     * 
     * @type {Array<DescriptionOfACompany>}
     * @memberof RankCompetitorList
     */
    competitors: Array<DescriptionOfACompany>;
}

/**
 * Check if a given object implements the RankCompetitorList interface.
 */
export function instanceOfRankCompetitorList(value: object): value is RankCompetitorList {
    if (!('competitors' in value) || value['competitors'] === undefined) return false;
    return true;
}

export function RankCompetitorListFromJSON(json: any): RankCompetitorList {
    return RankCompetitorListFromJSONTyped(json, false);
}

export function RankCompetitorListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RankCompetitorList {
    if (json == null) {
        return json;
    }
    return {
        
        'competitors': ((json['competitors'] as Array<any>).map(DescriptionOfACompanyFromJSON)),
    };
}

export function RankCompetitorListToJSON(value?: RankCompetitorList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'competitors': ((value['competitors'] as Array<any>).map(DescriptionOfACompanyToJSON)),
    };
}

